export const C = {
    ADD_APPOINTMENT: "ADD_APPOINTMENT",
    REMOVE_APPOINTMENT: "REMOVE_APPOINTMENT",
    SET_QUERY: "SET_QUERY",
    FETCH_HOLIDAYS: "FETCH_HOLIDAYS",
    FETCH_HOLIDAYS_SUCCESS: "FETCH_HOLIDAYS_SUCCESS",
    FETCH_HOLIDAYS_FAILURE: "FETCH_HOLIDAYS_FAILURE"
}